spring.application.name=redis-lab
server.port=${SERVER_PORT:8081}
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD}
redislab.pubsub.listener.enabled=${REDIS_PUBSUB_LISTENER_ENABLED:true}
